AWSCloudformationTemplateFormatVersion: '2010-09-09'
Description: 'Create an S3 bucket and a pull pipeline'

Parameters:
  Environment:
    Type: String
    Description: 'The environment to deploy to'
    Default: 'test'
    AllowedValues:
      - 'test'
      - 'staging'
      - 'prod'
    ConstraintDescription: 'Must specify dev, staging, or prod'

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::StackName}-${Environment}-bucket'
    Tags:
      - Key: 'Environment'
        Value: !Ref Environment

  Outputs:
    BucketName:
      Description: 'The name of my S3 bucket'
      Value: !Ref MyS3Bucket
      