name: Lambda CICD Pipeline
on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'

# defines the jobs for the GitHub Actions workflow

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
    - name: actions/checkout
      uses: actions/checkout@v2

# sets up Python 3.13 environment

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: 3.13

# installs the dependencies for the lambda function

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r lambda/requirements.txt -t lambda/

 # sets up the AWS credentials for the GitHub Actions workflow

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

# zips the lambda function and updates the lambda function code

    - name: Deploy Lambda function
      run: |
        cd lambda
        zip -r lambda.zip .
        aws lambda update-function-code --function-name Test_CICD_Lambda --zip-file fileb://lambda.zip